import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import axios from 'axios'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })


export default function Home() {

  const [data, setData] = useState({});
  const [location, setLocation] = useState('');
  const [weather, setWeather] = useState();
  const [errorMessage, setErrorMessage] = useState('');
  
  const [feelsLike, setFeelsLike] = useState();
  const [temp, setTemp] = useState();
  const [gust, setGust] = useState();
 
 


  var apiKey = "3185e01f5a0c36ccf41b0574a99258a4";
  var lang = "kr";
  var units = "metric";
  const url = `https://api.openweathermap.org/data/2.5/weather?q=${location}&units=${units}&appid=${apiKey}&lang=${lang}&exclude={hourly,daily}`;

  const searchLocation = (event) => {
    if (event.key === "Enter"){
      axios.get(url)
        .then((response) =>{
          //clear the input text
          console.clear();
          setData(response.data)
          console.log(response.data)
          setWeather(response.data.weather)
          setTemp(response.data.main.temp)
          setFeelsLike(response.data.main.feels_like)
          setGust(response.data.wind_gust)
          setErrorMessage("")
        }).catch(err => {
          console.log(err)
          setErrorMessage("Please set another location")
          setData({})
          setWeather()

        })
        //once you hit enter, it clears the location input
        setLocation('')
    }
  }


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {errorMessage}
       <input 
        value={location}
        onChange={event => setLocation(event.target.value)}
        placeholder="Enter location"
        onKeyDown={searchLocation}
        type="text"
       />
       {data.name}
       {temp}°C
       {feelsLike}°C
       {gust}m/s



        {/* {data.main.temp}°C
        {data.main.feels_like}°C
        {data.wind.gust}m/s */}
       
       

       {
        weather && weather.map((w, index)=>{
          return(
            <div key={index}>
              <div>{w.description}</div>
              <div>{w.main}</div>
            </div>
          )
        })
       }

      </main>
    </>
  )
}
